# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
- init: npm ci
  before: npm i -g commitizen && git config --global user.email $GIT_AUTHOR_EMAIL
